Added missing bits in PlatformInfo
virtee/sev pull request #164
Opened 2024-03-20 07:54 UTC by its-luca

Added ECC, RAPL and Ciphertext hiding bits to PlatformInfo, as defined in Table 23 of 
https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf

2024-03-20 14:33 UTC, tylerfanelli commented
@its-luca Thanks! Can you please add a `Signed-off-by` line to the commits?

2024-03-20 15:11 UTC, tylerfanelli commented
@larrydewey Has `PLATFORM_INFO` changed?

2024-03-20 15:31 UTC, its-luca commented
@tylerfanelli  done

2024-03-22 19:38 UTC, DGonzalezVillal requested changes
The change does match the spec! just a couple of comments, but besides that it looks good to me!

2024-03-22 19:38 UTC, DGonzalezVillal commented on src/firmware/guest/types/snp.rs
> +    /// Bit 3 indicates if RAPL is disabeld.
```suggestion
    /// Bit 3 indicates if RAPL is disabled.
```

2024-03-22 19:38 UTC, DGonzalezVillal commented on src/firmware/guest/types/snp.rs
> +
```suggestion
    pub smt_enabled, _: 0, 0;
    /// Returns the bit state of TSME.
    pub tsme_enabled, _: 1, 1;
    /// Indicates that the platform is currently using ECC memory
    pub ecc_enabled, _: 2, 2;
    /// Indicates that the RAPL feature is disabled
    pub rapl_disabled, _: 3, 3;
    /// Indicates that ciphertext hiding is enabled
    pub ciphertext_hiding_enabled, _: 4, 4;
    /// reserved
    reserved. _: 5, 63;
```
I don't know if this matters too much, but in other structs we include reserved fields. Thoughts on that @larrydewey

2024-03-26 18:09 UTC, its-luca commented
i applied the requested changes

2024-03-26 18:43 UTC, larrydewey commented
> @larrydewey Has `PLATFORM_INFO` changed?

Nope, it looks like this was a typo which was never caught.

2024-03-26 18:46 UTC, larrydewey requested changes

2024-03-26 18:46 UTC, larrydewey commented on src/firmware/guest/types/snp.rs
> +    reserved. _: 5, 63;
```suggestion
    reserved, _: 5, 63;
```
This is why a bunch of the tests are not passing.

2024-03-26 18:54 UTC, its-luca commented
Sorry about that. I should not have done that from the web interface...

2024-03-26 19:52 UTC, tylerfanelli commented
Can you squash the commits?

2024-03-26 21:25 UTC, larrydewey approved these changes

2024-03-26 22:09 UTC, DGonzalezVillal commented
@its-luca Did you mean to remove the reserved bit in the bitfield again?

2024-03-27 06:29 UTC, its-luca commented
@DGonzalezVillal  No I did not, thanks for catching that!. I embarrassingly pressed "drop" instead of squash... . I am really sorry for the overhead. Now it should be fixed.

2024-03-27 17:11 UTC, DGonzalezVillal approved these changes
LGTM!

2024-03-27 17:12 UTC, DGonzalezVillal commented
> @DGonzalezVillal No I did not, thanks for catching that!. I embarrassingly pressed "drop" instead of squash... . I am really sorry for the overhead. Now it should be fixed.

No worries! Thank you for the PR!

2024-03-28 12:45 UTC, larrydewey approved these changes

2024-03-28 12:45 UTC, merged