Updated OVMF and VCPU handling
virtee/sev pull request #196
Opened 2024-06-18 16:19 UTC by DGonzalezVillal

Updated OVMF in measurement to be able to handle the new section introduced.

Added ability to convert from i32  (VCPU signature) into a VCPU type.

2024-07-26 16:15 UTC, larrydewey submitted a review, later dismissed
Looks pretty good to me. The changes suggested are not required.

2024-07-30 16:59 UTC, larrydewey requested changes
Some minor changes, but overall looks good.

2024-07-30 16:59 UTC, larrydewey commented on src/measurement/gctx.rs
> +            return Err(MeasurementError::GCTXError(GCTXError::InvalidPageSize(
```suggestion
            return Err(GCTXError::InvalidPageSize(...).into())
```

2024-07-30 16:59 UTC, larrydewey commented on src/measurement/gctx.rs
> +        self.ld = SnpLaunchDigest::try_from(sha384(&page_info).as_slice())?;
```suggestion
        self.ld = sha384(&page_info).as_slice().try_into()?;
```

2024-07-30 16:59 UTC, larrydewey commented on src/measurement/gctx.rs
> +                    Err(MeasurementError::GCTXError(GCTXError::MissingData))
```suggestion
                    Err(GCTXError::MissingData.into())
```

2024-07-30 16:59 UTC, larrydewey commented on src/measurement/gctx.rs
> +                    Err(MeasurementError::GCTXError(GCTXError::MissingData))
```suggestion
                    Err(GCTXError::MissingData.into())
```

2024-07-30 16:59 UTC, larrydewey commented on src/measurement/gctx.rs
> +                    Err(MeasurementError::GCTXError(GCTXError::MissingBlockSize))
```suggestion
                    Err(GCTXError::MissingBlockSize.into())
```

2024-07-30 21:11 UTC, larrydewey approved these changes
LGTM!

2024-07-31 02:39 UTC, tylerfanelli approved these changes

2024-07-31 02:40 UTC, tylerfanelli commented
Closes #194

2024-07-31 02:40 UTC, merged