Updating Errors to correctly use SEV API errors
virtee/sev pull request #228
Opened 2024-09-10 21:55 UTC by DGonzalezVillal

The AMD PSP provides defined SEV errors in the API with clear codes and mistakes. The library currently only bubbles up IO errors and not the correct SEV error when IOCTL calls fail. This commit rearranges the error file to use SEV errors correctly, and then changes the way IOCTL calls returns errors, so that the appropriate SEV error is bubbled up when an error is encountered.

2024-09-11 16:43 UTC, larrydewey requested changes

2024-09-11 16:43 UTC, larrydewey commented on src/error.rs
> +            _ => FirmwareError::UnknownSevError(error),
```suggestion
            0x00 => FirmwareError::IoError(io::Error::last_os_error()),
            0x01..0x27 => FirmwareError::KnownSevError(error.into()),
            _ => FirmwareError::UnknownSevError(error),
```

2024-09-11 16:43 UTC, larrydewey commented on src/error.rs
> +            FirmwareError::IoError(_) => -0x01,
```suggestion
            FirmwareError::UnknownSevError(_) | FirmwareError::IoError(_) => -0x01,
```

2024-09-11 16:43 UTC, larrydewey commented on src/firmware/host/mod.rs
> +                _ => return Err(FirmwareError::KnownSevError(SevError::InvalidPlatformState))?,
```suggestion
                _ => return Err(SevError::InvalidPlatformState)?,
```

Can't we just do this?

2024-09-11 16:43 UTC, larrydewey commented on src/launch/sev.rs
> +            if let FirmwareError::KnownSevError(SevError::InvalidLen) = err {
Do we need both layers of error here?

2024-09-12 19:08 UTC, larrydewey commented on src/error.rs
> +            SevError::UnknownError => 0x00,
Did we want this to be -1

2024-09-12 19:09 UTC, larrydewey approved these changes
LGTM

2024-10-22 21:41 UTC, tylerfanelli commented
@larrydewey can you re-review?

2024-10-28 21:56 UTC, larrydewey approved these changes

2024-11-04 03:51 UTC, tylerfanelli approved these changes

2024-11-04 03:52 UTC, merged