Adding deprecation flags for SEV components and bumping to 5.1
virtee/sev pull request #253
Opened 2024-11-25 21:30 UTC by DGonzalezVillal

As discussed, adding deprecation flags for SEV components, so that it can be removed in the next 6.0 release. Bumping to 5.1 so that people can still use 5.0.0 without compilation warnings if they are using SEV.

2024-11-25 21:35 UTC, larrydewey approved these changes
LGTM

2024-11-25 21:36 UTC, DGonzalezVillal commented
Adding WIP flag, waiting for 5.0 release first

2024-11-25 22:25 UTC, tylerfanelli commented
Set to draft PR as well, so this can't be merged.

2024-12-16 20:59 UTC, DGonzalezVillal commented
Can be merged now if we want this still

2024-12-17 02:10 UTC, tylerfanelli requested changes

2024-12-17 02:10 UTC, tylerfanelli commented on src/certs/sev/builtin/mod.rs
> -
You left a `deprecated` note on this module in `src/certs/mod.rs`. Why are these deprecation notes also needed?

2025-01-06 21:02 UTC, larrydewey approved these changes

2025-01-06 21:04 UTC, tylerfanelli commented
Let's hold off on this until sev-5.0.0 is packaged for distros. Will revisit this at that point.

2025-02-25 19:10 UTC, tylerfanelli commented
After further consideration and discussing with my some other stakeholders, I don't think it's the best time to do this.

2025-04-24 16:22 UTC, closed without merging