Adding AttestationReport Verification with Certificate only
virtee/sev pull request #266
Opened 2024-12-19 19:15 UTC by DGonzalezVillal

We currently only offer report verification with a full chain being provided. Although it is safest to provide a whole chain to verify the whole root of trust, there are cases people might want to divide the process into individual steps. This allows users to verify the report with what should be an already verified versioned endorsement key.

I also renamed the VCEK to VEK since we no offer support for both the VLEK and VCEK.

2024-12-20 06:16 UTC, tylerfanelli requested changes

2024-12-20 06:16 UTC, tylerfanelli commented on src/firmware/guest/types/snp.rs
> +        // [spec]: https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/57230.pdf
I don't think these two links are necessary. Rather, you can mention "see specifications _X_ and _Y_".

2025-01-13 20:57 UTC, DGonzalezVillal commented
@tylerfanelli @larrydewey Re-review please

2025-01-31 23:11 UTC, tylerfanelli approved these changes

2025-01-31 23:11 UTC, merged