policy: Fixing bitfield bugs
virtee/sev pull request #51
Opened 2022-12-01 21:32 UTC by larrydewey

Previously there was no way to access the policy or platform info fields. This patches those fields.

Signed-off-by: Larry Dewey <larry.dewey@amd.com>

2022-12-01 22:20 UTC, fitzthum approved these changes
LGTM

2022-12-01 22:20 UTC, fitzthum commented on src/firmware/linux/guest/types.rs
> +    pub smt, _: 16, 16;
Would it be clearer if this were `smt_allowed`?

2022-12-02 03:31 UTC, tylerfanelli requested changes
Although the actual code LGTM, do you think the comments should change? Instead of having something like:
`/// The API_MINOR value contained in the 64 bit value`

I think that the comment should explain what that value means, for example:
`/// API_MINOR field: Indicates the minor API version`

With this, someone reading the source code can have an idea on what each value indicates without having to look it up in the SNP spec.

What do you think?

2022-12-05 18:02 UTC, larrydewey commented
> Although the actual code LGTM, do you think the comments should change? Instead of having something like: `/// The API_MINOR value contained in the 64 bit value`
> 
> I think that the comment should explain what that value means, for example: `/// API_MINOR field: Indicates the minor API version`
> 
> With this, someone reading the source code can have an idea on what each value indicates without having to look it up in the SNP spec.
> 
> What do you think?

Yeah, that is a pretty easy set of changes. I have applied it in the latest commit. Let me know what you think.

2022-12-05 19:45 UTC, tylerfanelli approved these changes
Thanks!

2022-12-05 19:45 UTC, merged