firmware/guest: Make FFICertTableEntry::parse_table() public
virtee/sev pull request #60
Opened 2023-02-17 05:48 UTC by tylerfanelli

I don't care much for `FFICertTableEntry` being publicly available to users, as it should never be used. However, the `parse_table()` method associated with the struct is quite useful for deserializing bytes into a cert table.

Maybe we should separate this function from `FFICertTableEntry` and only make `parse_table()` public?

2023-02-17 18:57 UTC, larrydewey commented
> I don't care much for `FFICertTableEntry` being publicly available to users, as it should never be used. However, the `parse_table()` method associated with the struct is quite useful for deserializing bytes into a cert table.

I agree, I would much rather not have this be publicly listed. Because this is a static method, we could just rip it out of the `impl` here, and re-export the function specificially via the `.../host/types.rs` module. I would prefer this to the guest module, as it is defined as a linux host type in the FFI.

> Maybe we should separate this function from `FFICertTableEntry` and only make `parse_table()` public?

That would make sense to me, with the exception I mentioned above.

2023-02-18 06:32 UTC, tylerfanelli commented
> > I don't care much for `FFICertTableEntry` being publicly available to users, as it should never be used. However, the `parse_table()` method associated with the struct is quite useful for deserializing bytes into a cert table.
> 
> I agree, I would much rather not have this be publicly listed. Because this is a static method, we could just rip it out of the `impl` here, and re-export the function specificially via the `.../host/types.rs` module. I would prefer this to the guest module, as it is defined as a linux host type in the FFI.
> 
> > Maybe we should separate this function from `FFICertTableEntry` and only make `parse_table()` public?
> 
> That would make sense to me, with the exception I mentioned above.

As I mentioned on our previous message, since `parse_table()` itself takes an `FFICertTableEntry` as an arg, we would need to publicize `FFICertTableEntry` anyway.

I could make a further note that from a user of this library, `FFICertTableEntry` should really only be used for its `parse_table()` method, and even then to exercise caution.

2023-02-21 19:48 UTC, larrydewey commented
We talked about this via Element, but just to document the discussion, there were a few ways to go about implementing the change without publicly listing the type. We are opting to go with a façade function and looking to create an enum to abstract what the user may send to that function and then casting those data pieces to the Linux FFI type before calling the internal function.

*Example:*
```rust
/// A data structure representing the possible data types which may be passed to
/// the parse_data function.
pub enum RawData {
    /// A pointer to a byte buffer
    Pointer(*mut u8),

    /// A heap allocation of bytes.
    Vector(Vec<u8>),
}

// ...

///
/// This is a façade for calling down to the private function which uses the Linux FFI wrapped type.
///
/// # Safety
///
/// This is unsafe because it calls an unsafe function to parse the Vec<CertTableEntry> from the data
/// which was provided.
pub unsafe fn parse_table(data: RawData) -> Result<Vec<CertTableEntry>, uuid::Error> {
    match data {
        RawData::Pointer(pointer) => {
            FFICertTableEntry::parse_table(pointer as *mut FFICertTableEntry)
        }
        RawData::Vector(vector) => {
            let mut copied_data = vector;
            FFICertTableEntry::parse_table(copied_data.as_mut_ptr() as *mut FFICertTableEntry)
        }
    }
}
```

2023-02-21 20:31 UTC, larrydewey requested changes
See previous comments

2023-02-22 05:40 UTC, tylerfanelli commented
@larrydewey Yes, I see now. Will change.

2023-03-03 06:43 UTC, tylerfanelli commented
Closing this as after second thoughts, I think this should remain a private function.

2023-03-03 06:43 UTC, closed without merging