Declare minimal Rust version in Cargo.toml.
virtee/sev pull request #89
Opened 2023-07-17 13:42 UTC by sarutak

This PR proposed to declare minimal Rust version in `Cargo.toml`.
Explicitly declaring the minimal version can help developers.

2023-07-19 17:22 UTC, larrydewey commented
Thanks for the work here @sarutak! @tylerfanelli I know we have discussed this a little bit. Are we still in agreement about changing the enums using custom discriminant values to lower the expected rust version dependency?

2023-07-20 03:06 UTC, tylerfanelli commented
@larrydewey #83 shows that a stock Ubuntu image uses a Rust version < 1.66. I feel that we should probably try to align the project with the "standard" Rust version on most distributions.

2023-07-20 05:05 UTC, sarutak commented
Hmm, Ubuntu 22.04 already provides Rust 1.66.1 right?
https://packages.ubuntu.com/jammy/devel/rustc

2023-07-20 05:23 UTC, tylerfanelli commented
My mistake, the issue I mentioned was for Rust 1.70, which isn't the standard on Ubuntu 22.04 yet.

2023-07-20 05:25 UTC, tylerfanelli commented
CC @larrydewey

Shouldn't this commit cause some issues due to the fact that the `Enum` mentioned in #83 uses features only available in Rust versions > 1.65?

2023-07-20 15:02 UTC, tylerfanelli commented
> I know this PR is setting it to 1.66, which I think still is broken using the custom discriminant feature, but maybe I had the release version wrong? Regardless, I think we were both in agreement that whatever the release version we set should remove the use of that feature, and the downgrade to allow older releases work. This is still our plan, correct?

I thought so too, but the `clippy` checks are still working?

2023-07-20 21:08 UTC, larrydewey commented
@tylerfanelli So it looks like version 1.66 was when the issue was patched. Any Rust version <= 1.65 will break. @sarutak where you made the PR for this, do you have any complaints with our downgrading the Rust version to at least 1.65?

2023-07-20 21:32 UTC, larrydewey requested changes
If we are agreed, we will want to set the value to this, and implement the following changes:

From:
https://github.com/virtee/sev/blob/700b82054b73c186d89a393380768a60298fc275/src/error.rs#L360-L372

To:
```rust
...
 /// The AEAD algorithm would have overflowed 
 AEADOFlow, // 0x001D 
 
 /// A placeholder between AEDOFlow and RBModeExited
 _ReservedDoNotUse, // 0x001E
 /// A Mailbox mode command was sent while the SEV FW was in Ring Buffer 
 /// mode. Ring Buffer mode has been exited; the Mailbox mode command 
 /// has been ignored. Retry is recommended. 
 RbModeExited, // 0x001F 
  
 /// The RMP must be reinitialized. 
 RMPInitRequired, // 0x0020 
...
```

AND

From:
https://github.com/virtee/sev/blob/700b82054b73c186d89a393380768a60298fc275/src/error.rs#L430-L435

To:
```rust
...
             Error::AEADOFlow => "The AEAD algorithm would have overflowed.",
             Error::_ReservedDoNotUse => "If you are seeing this, something his HORRIBLY wrong!",
             Error::RbModeExited => "A Mailbox mode command was sent while the SEV FW was in Ring Buffer \ 
                                     mode. Ring Buffer mode has been exited; the Mailbox mode command has \ 
                                     been ignored. Retry is recommended.", 
...
```

FINALLY

From:
https://github.com/virtee/sev/blob/700b82054b73c186d89a393380768a60298fc275/src/error.rs#L533-L534

To:
```rust
...
             0x1D => Error::AEADOFlow,
             0x1E => Error::_ReservedDoNotUse,
             0x1F => Error::RbModeExited,
...
```

2023-07-20 21:32 UTC, larrydewey commented on Cargo.toml
> +rust-verson = "1.66.1"
```suggestion
rust-verson = "1.65.0"
```

2023-07-20 21:39 UTC, tylerfanelli commented
LGTM.

2023-07-20 21:43 UTC, DGonzalezVillal commented
Hi, from what I'm understanding we want to downgrade the minimum version to 1.65 because it'll encompass most distributions shipped versions? What distros ship with rust version under 1.66? I've checked a few known distros and I've seen most of them ship with versions > 1.65.

2023-07-20 21:49 UTC, larrydewey commented
So after talking it over with Diego I deleted my previous comment. His point is very valid. it looks like even Ubuntu 20.04 created a security backport to upgrade Rust to 1.66.1, so at this point I think it would make the most sense to move forward with 1.66.1

2023-07-20 21:50 UTC, larrydewey approved these changes
LGTM!

2023-07-20 21:50 UTC, tylerfanelli commented
Agreed.

Fedora shipping 1.70: https://src.fedoraproject.org/rpms/rust

2023-07-20 21:50 UTC, tylerfanelli approved these changes

2023-07-20 21:51 UTC, merged